package scala.collection.immutable.vectorbenchmarks.rrbvector.xunbalanced

import scala.collection.immutable.vectorbenchmarks.genericbenchmarks.ParMapBenchmarks
import scala.collection.immutable.vectorutils.VectorGeneratorType


class RRBVectorParMapIntBenchmark extends ParMapBenchmarks with RRBVectorAbstractBenchmark[Int] with VectorGeneratorType.IntGenerator

