package scala.collection.immutable.vectorbenchmarks.genrrbvector

import scala.collection.immutable.vectorbenchmarks.GenRRBVectorBenchmark
import scala.collection.immutable.vectorbenchmarks.genericbenchmarks.SplitBenchmarks
import scala.collection.immutable.vectorutils.VectorGeneratorType


abstract class GenRRBVectorAbstractSplitBenchmark[A] extends SplitBenchmarks[A] with GenRRBVectorBenchmark[A]

class GenRRBVectorSplitIntBenchmark extends GenRRBVectorAbstractSplitBenchmark[Int] with VectorGeneratorType.IntGenerator

class GenRRBVectorSplitAnyRefBenchmark extends GenRRBVectorAbstractSplitBenchmark[AnyRef] with VectorGeneratorType.AnyRefGenerator

